/* Generated by cbindgen from src/ffi.rs. Do not edit by hand. */

#ifndef BRIDGE_ADB_H
#define BRIDGE_ADB_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Deliberately not POSIX `errno` values: those aren't reliably portable
 * across the platforms this project targets (Android, desktop
 * Linux/macOS, eventually Windows), so this is a small self-contained
 * status code instead.
 */
typedef enum BridgeAdbStatus {
  BRIDGE_ADB_STATUS_OK = 0,
  BRIDGE_ADB_STATUS_ERROR_INVALID_ARGUMENT = 1,
  BRIDGE_ADB_STATUS_ERROR_TIMED_OUT = 2,
  BRIDGE_ADB_STATUS_ERROR_IO = 3,
} BridgeAdbStatus;

/**
 * Opaque handle to a connected adb `track-devices` client.
 */
typedef struct BridgeAdbClient BridgeAdbClient;

typedef struct BridgeAdbDevice {
  /**
   * Null-terminated. Owned by the enclosing `BridgeAdbDeviceList`; do
   * not free individually.
   */
  char *serial;
  /**
   * Null-terminated. Owned by the enclosing `BridgeAdbDeviceList`; do
   * not free individually.
   */
  char *state;
} BridgeAdbDevice;

typedef struct BridgeAdbDeviceList {
  struct BridgeAdbDevice *devices;
  uintptr_t count;
} BridgeAdbDeviceList;

/**
 * Connects to an adb server at `host:port` (typically `"127.0.0.1"`,
 * `5037`). `timeout_ms` bounds how long this waits for the connection
 * and initial handshake: a negative value waits indefinitely, otherwise
 * it's a millisecond bound.
 *
 * On success, returns `BRIDGE_ADB_OK` and writes a caller-owned handle
 * to `*out_client`, to be freed with `bridge_adb_disconnect`. On
 * failure, returns a non-OK status and leaves `*out_client` untouched.
 *
 * # Safety
 * `host` must be a valid, null-terminated C string. `out_client` must be
 * a valid, writable pointer.
 */
enum BridgeAdbStatus bridge_adb_connect(const char *host,
                                        uint16_t port,
                                        int64_t timeout_ms,
                                        struct BridgeAdbClient **out_client);

/**
 * Blocks until the next device-list snapshot arrives and writes it to
 * `out_list`. Returns `true` on success, `false` if the connection
 * closed or an error occurred (in which case `out_list` is left
 * untouched).
 *
 * # Safety
 * `client` must be a valid pointer returned by `bridge_adb_connect` and
 * not yet passed to `bridge_adb_disconnect`. `out_list` must be a valid,
 * writable pointer to a `BridgeAdbDeviceList`.
 */
bool bridge_adb_next_snapshot(struct BridgeAdbClient *client, struct BridgeAdbDeviceList *out_list);

/**
 * Frees a device list previously written by `bridge_adb_next_snapshot`.
 *
 * # Safety
 * `list` must be a list previously written by `bridge_adb_next_snapshot`,
 * and must not be freed more than once.
 */
void bridge_adb_free_device_list(struct BridgeAdbDeviceList list);

/**
 * Disconnects and frees a client handle. `client` must not be used
 * afterward.
 *
 * # Safety
 * `client` must be a valid pointer returned by `bridge_adb_connect`, not
 * already passed to this function.
 */
void bridge_adb_disconnect(struct BridgeAdbClient *client);

#endif  /* BRIDGE_ADB_H */
