/* Generated by cbindgen from src/lib.rs. Do not edit by hand. */

#ifndef RENDERER_CAPI_H
#define RENDERER_CAPI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Deliberately not POSIX `errno` values: those aren't reliably portable
 * across the platforms this project targets (Android, desktop
 * Linux/macOS, eventually Windows), so this is a small self-contained
 * status code instead — same convention as `bridge-adb`'s C ABI.
 */
typedef enum RendererCapiStatus {
  RENDERER_CAPI_STATUS_OK = 0,
  RENDERER_CAPI_STATUS_ERROR_INVALID_ARGUMENT = 1,
  /**
   * Any Vulkan/driver-level failure (instance/device creation,
   * pipeline creation, submission, ...). Not split further yet since
   * no caller has needed to distinguish cases.
   */
  RENDERER_CAPI_STATUS_ERROR_VULKAN = 2,
} RendererCapiStatus;

/**
 * Runs a single compute shader dispatch end-to-end: creates a Vulkan
 * instance + device, loads `spirv` as a compute shader, binds a single
 * storage buffer of exactly `out_buffer_len` bytes at binding 0,
 * dispatches `(workgroup_count_x, workgroup_count_y, workgroup_count_z)`
 * workgroups, waits for completion, and copies the buffer's final
 * contents into `out_buffer`.
 *
 * # Safety
 * `spirv` must point to `spirv_len` valid, readable bytes. `out_buffer`
 * must point to `out_buffer_len` valid, writable bytes.
 */
enum RendererCapiStatus renderer_capi_run_compute_sample(const uint8_t *spirv,
                                                         uintptr_t spirv_len,
                                                         uint32_t workgroup_count_x,
                                                         uint32_t workgroup_count_y,
                                                         uint32_t workgroup_count_z,
                                                         uint8_t *out_buffer,
                                                         uintptr_t out_buffer_len);

#endif  /* RENDERER_CAPI_H */
